name: Infrastructure Code Security Scan with Checkov

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  check-security:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov
        run: checkov -d . --quiet

      - name: Run Checkov
        run: checkov -d . --quiet --skip-check CKV_AWS_144,CKV_AWS_18
